# Generated by Django 6.0 on 2026-05-06 19:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transporteurs', '0002_entrepot_chauffeur_date_naissance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChauffeurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permis', models.CharField(blank=True, max_length=30)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('note_moyenne', models.FloatField(default=5.0)),
                ('disponible', models.BooleanField(default=True)),
                ('position_actuelle', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('derniere_position_maj', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chauffeur_profile', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur_profile', to='transporteurs.vehicule')),
            ],
            options={
                'verbose_name': 'Profil Chauffeur',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(blank=True, default='', max_length=150)),
                ('adresse', models.TextField(blank=True)),
                ('note_fidelite', models.IntegerField(default=3)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Client',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('client', 'Client'), ('chauffeur', 'Chauffeur')], default='client', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.CharField(blank=True, default='', max_length=255)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
            },
        ),
    ]
