# Generated by Django 5.1.15 on 2026-05-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_statut_70e46f_idx',
            old_name='tickets_tic_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_auteur__efa583_idx',
            old_name='tickets_tic_auteur_idx',
        ),
    ]
