# Generated by Django 5.1.15 on 2026-05-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_tickets_tic_statut_idx_tickets_tic_statut_70e46f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='categorie',
            field=models.CharField(choices=[('reclamation', 'Réclamation'), ('assistance', "Demande d'assistance"), ('incident', 'Incident'), ('retard', 'Retard de livraison'), ('retour', 'Retour produit'), ('livraison', 'Livraison'), ('paiement', 'Paiement'), ('technique', 'Technique'), ('compte', 'Compte'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
