# Generated by Django 6.0 on 2026-05-05 18:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transporteur',
                'verbose_name_plural': 'Transporteurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(choices=[('camion', 'Camion'), ('fourgon', 'Fourgon'), ('moto', 'Moto'), ('voiture', 'Voiture')], default='camion', max_length=20)),
                ('capacite_kg', models.FloatField(help_text='Capacité en kilogrammes')),
                ('disponible', models.BooleanField(default=True)),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='transporteurs.transporteur')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('permis', models.CharField(max_length=30)),
                ('disponible', models.BooleanField(default=True)),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chauffeurs', to='transporteurs.transporteur')),
                ('vehicule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur', to='transporteurs.vehicule')),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
            },
        ),
    ]
