# Generated by Django 5.1.15 on 2026-05-15 20:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicule_type', models.CharField(choices=[('MOTO', 'Moto'), ('VOITURE', 'Voiture'), ('CAMIONNETTE', 'Camionnette'), ('CAMION', 'Camion')], default='MOTO', max_length=15)),
                ('plaque', models.CharField(max_length=20, unique=True)),
                ('capacite_kg', models.FloatField(default=50.0)),
                ('couleur_vehicule', models.CharField(blank=True, max_length=50)),
                ('photo_vehicule', models.ImageField(blank=True, null=True, upload_to='transporteurs/vehicules/')),
                ('permis_conduire', models.FileField(blank=True, null=True, upload_to='transporteurs/permis/')),
                ('assurance', models.FileField(blank=True, null=True, upload_to='transporteurs/assurance/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('is_on_delivery', models.BooleanField(default=False)),
                ('position_actuelle', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('derniere_maj_position', models.DateTimeField(blank=True, null=True)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('nombre_avis', models.IntegerField(default=0)),
                ('nombre_livraisons', models.IntegerField(default=0)),
                ('revenus_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporteur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transporteur',
                'verbose_name_plural': 'Transporteurs',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
