# Generated by Django 6.0 on 2026-05-15 18:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicule_type', models.CharField(choices=[('MOTO', 'Moto'), ('VOITURE', 'Voiture'), ('CAMIONNETTE', 'Camionnette'), ('CAMION', 'Camion')], default='MOTO', max_length=20)),
                ('capacite_kg', models.FloatField(default=0.0)),
                ('plaque', models.CharField(blank=True, default='', max_length=20)),
                ('is_available', models.BooleanField(default=False)),
                ('position_actuelle', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('is_verified', models.BooleanField(default=False)),
                ('note_moyenne', models.FloatField(default=5.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporteur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transporteur',
                'verbose_name_plural': 'Transporteurs',
            },
        ),
    ]
