# Generated by Django 6.0 on 2026-05-06 16:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('capacite_m2', models.FloatField(default=0, help_text='Superficie en m²')),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='note_moyenne',
            field=models.FloatField(default=5.0, help_text='Note sur 5'),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='region_couverture',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='annee_fabrication',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='couleur',
            field=models.CharField(choices=[('blanc', 'Blanc'), ('gris', 'Gris'), ('bleu', 'Bleu'), ('rouge', 'Rouge'), ('noir', 'Noir'), ('autre', 'Autre')], default='blanc', max_length=20),
        ),
    ]
