# Generated by Django 5.1.15 on 2026-05-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteur',
            name='date_derniere_session',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='heure_debut_disponibilite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='minutes_travaillees_aujourd_hui',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='minutes_travaillees_mois',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='minutes_travaillees_semaine',
            field=models.IntegerField(default=0),
        ),
    ]
