# Generated by Django 6.0 on 2026-05-15 18:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(choices=[('accident', 'Accident'), ('retard', 'Retard'), ('colis_endommage', 'Colis endommagé'), ('panne', 'Panne véhicule'), ('vol', 'Vol / Perte'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_traitement', 'En traitement'), ('resolu', 'Résolu')], default='ouvert', max_length=20)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, help_text="Lieu de l'incident (GPS)", null=True, srid=4326)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('notes_resolution', models.TextField(blank=True, default='')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date_signalement'],
            },
        ),
    ]
