# Generated by Django 5.1.15 on 2026-05-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidentphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='type_incident',
            field=models.CharField(choices=[('accident', 'Accident'), ('retard', 'Retard'), ('colis_endommage', 'Colis endommagé'), ('panne', 'Panne véhicule'), ('vol', 'Vol / Perte'), ('client_absent', 'Client absent'), ('adresse_introuvable', 'Adresse introuvable'), ('autre', 'Autre')], default='autre', max_length=30),
        ),
    ]
