# Generated by Codex on 2026-06-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('incidents', '0003_alter_incident_type_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='commande',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='incidents',
                to='commandes.commande',
            ),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type_incident',
            field=models.CharField(
                choices=[
                    ('sos', 'SOS chauffeur'),
                    ('accident', 'Accident'),
                    ('retard', 'Retard'),
                    ('colis_endommage', 'Colis endommagé'),
                    ('panne', 'Panne véhicule'),
                    ('vol', 'Vol / Perte'),
                    ('client_absent', 'Client absent'),
                    ('adresse_introuvable', 'Adresse introuvable'),
                    ('autre', 'Autre'),
                ],
                default='autre',
                max_length=30,
            ),
        ),
    ]
