# Generated by Django 6.0 on 2026-05-05 18:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('vitesse_kmh', models.FloatField(default=0)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'Position Véhicule',
                'verbose_name_plural': 'Positions Véhicules',
                'ordering': ['-horodatage'],
            },
        ),
    ]
