# Generated by Django 6.0 on 2026-05-15 18:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fondateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fondateurs/logos/')),
                ('categorie', models.CharField(choices=[('SUPERMARCHE', 'Supermarché'), ('BOUTIQUE', 'Boutique'), ('PHARMACIE', 'Pharmacie'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('adresse', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('zone_livraison', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fondateur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fondateur',
                'verbose_name_plural': 'Fondateurs',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('categorie', models.CharField(blank=True, max_length=50)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fondateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='fondateurs.fondateur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='ProduitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/images/')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fondateurs.produit')),
            ],
        ),
    ]
