# Generated by Django 5.1.15 on 2026-05-15 20:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fondateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='boutiques/logos/')),
                ('categorie', models.CharField(choices=[('SUPERMARCHE', 'Supermarché'), ('BOUTIQUE', 'Boutique / Mode'), ('PHARMACIE', 'Pharmacie'), ('RESTAURATION', 'Restauration'), ('ELECTRONIQUE', 'Électronique'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('adresse', models.CharField(max_length=500)),
                ('ville', models.CharField(default='Casablanca', max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('zone_livraison', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('rayon_livraison_km', models.FloatField(default=5.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True)),
                ('horaires', models.JSONField(blank=True, default=dict)),
                ('frais_livraison_base', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('commande_minimum', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('note_moyenne', models.FloatField(default=0.0)),
                ('nombre_avis', models.IntegerField(default=0)),
                ('nombre_commandes', models.IntegerField(default=0)),
                ('document_verification', models.FileField(blank=True, null=True, upload_to='boutiques/docs/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fondateur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fondateur',
                'verbose_name_plural': 'Fondateurs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CodePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type_reduction', models.CharField(choices=[('POURCENTAGE', 'Pourcentage (%)'), ('MONTANT', 'Montant fixe (MAD)')], default='POURCENTAGE', max_length=15)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('montant_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('actif', models.BooleanField(default=True)),
                ('usage_max', models.IntegerField(default=100)),
                ('usage_count', models.IntegerField(default=0)),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('fondateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_promo', to='fondateurs.fondateur')),
            ],
            options={
                'verbose_name': 'Code Promo',
                'verbose_name_plural': 'Codes Promo',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('stock_alerte', models.IntegerField(default=5)),
                ('categorie', models.CharField(choices=[('ALIMENTAIRE', 'Alimentaire'), ('BOISSONS', 'Boissons'), ('HYGIENE', 'Hygiène & Beauté'), ('ELECTRONIQUE', 'Électronique'), ('VETEMENTS', 'Vêtements'), ('MEDICAMENTS', 'Médicaments'), ('MAISON', 'Maison & Déco'), ('SPORT', 'Sport'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('nombre_commandes', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fondateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='fondateurs.fondateur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/images/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fondateurs.produit')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
