# Generated by Django 6.0 on 2026-05-15 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type_remise', models.CharField(choices=[('POURCENTAGE', 'Pourcentage (%)'), ('FIXE', 'Montant fixe')], default='POURCENTAGE', max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('usage_max', models.IntegerField(blank=True, null=True)),
                ('usage_actuel', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fondateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_promo', to='fondateurs.fondateur')),
            ],
            options={
                'verbose_name': 'Code Promo',
                'verbose_name_plural': 'Codes Promo',
            },
        ),
    ]
