# Generated by Django 5.1.15 on 2026-05-21 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FondateurMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('logo', 'Logo'), ('banniere', 'Banniere boutique'), ('photo', 'Photo boutique')], default='photo', max_length=10)),
                ('image', models.ImageField(upload_to='boutiques/medias/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fondateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='fondateurs.fondateur')),
            ],
            options={
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
