# Generated by Django 5.1.15 on 2026-05-21 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('boutique_id', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('VERROUILLEE', 'Verrouillée'), ('COMMANDEE', 'Commandée'), ('ANNULEE', 'Annulée')], default='OUVERTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_groupe_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Groupe',
                'verbose_name_plural': 'Sessions Groupe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembreGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejoint_le', models.DateTimeField(auto_now_add=True)),
                ('est_pret', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_groupe_rejointes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='mode_groupe.sessiongroupe')),
            ],
            options={
                'verbose_name': 'Membre Groupe',
                'unique_together': {('session', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='ArticleGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_id', models.PositiveIntegerField()),
                ('nom_produit', models.CharField(max_length=255)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='mode_groupe.membregroupe')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='mode_groupe.sessiongroupe')),
            ],
            options={
                'verbose_name': 'Article Groupe',
            },
        ),
    ]
