# Generated by Django 5.1.15 on 2026-05-15 20:14

import commandes.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fondateurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=commandes.models.generate_reference, editable=False, max_length=20, unique=True)),
                ('adresse_livraison', models.CharField(max_length=500)),
                ('location_livraison', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('etage_porte', models.CharField(blank=True, max_length=100)),
                ('instructions_livraison', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('EN_PREPARATION', 'En préparation'), ('EN_ROUTE', 'En route'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('mode_paiement', models.CharField(choices=[('CARTE', 'Carte bancaire (Stripe)'), ('CASH', 'Cash à la livraison')], default='CASH', max_length=10)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200)),
                ('est_paye', models.BooleanField(default=False)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('reduction', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('code_promo_utilise', models.CharField(blank=True, max_length=20)),
                ('livraison_immediate', models.BooleanField(default=True)),
                ('livraison_programmee', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('livree_at', models.DateTimeField(blank=True, null=True)),
                ('est_signale', models.BooleanField(default=False)),
                ('motif_signalement', models.TextField(blank=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='commandes_client', to=settings.AUTH_USER_MODEL)),
                ('fondateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='fondateurs.fondateur')),
                ('transporteur', models.ForeignKey(blank=True, limit_choices_to={'role': 'TRANSPORTEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_transport', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='fondateurs.produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cible_type', models.CharField(choices=[('TRANSPORTEUR', 'Transporteur'), ('FONDATEUR', 'Fondateur')], max_length=15)),
                ('note', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_donnés', to=settings.AUTH_USER_MODEL)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'unique_together': {('commande', 'auteur', 'cible_type')},
            },
        ),
    ]
