# Generated by Django 6.0 on 2026-05-05 18:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('transporteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('adresse_depart', models.TextField()),
                ('point_depart', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('adresse_destination', models.TextField()),
                ('point_destination', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('type_marchandise', models.CharField(choices=[('electronique', 'Électronique'), ('alimentaire', 'Alimentaire'), ('textile', 'Textile'), ('chimique', 'Chimique'), ('construction', 'Matériaux de construction'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('poids_kg', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('date_souhaitee', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('affectee', 'Affectée'), ('en_cours', 'En cours de livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('itineraire', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('duree_estimee_min', models.IntegerField(blank=True, null=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='transporteurs.chauffeur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='clients.client')),
                ('transporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='transporteurs.transporteur')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='transporteurs.vehicule')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
