# Generated by Django 6.0 on 2026-05-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='notes_client',
            field=models.TextField(blank=True, default='', help_text='Notes ou instructions spéciales du client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='prix_estime',
            field=models.FloatField(blank=True, help_text='Prix estimé en MAD', null=True),
        ),
    ]
