# Generated by Django 6.0 on 2026-05-15 18:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('entreprise', models.CharField(blank=True, default='', max_length=150)),
                ('note_fidelite', models.IntegerField(default=3, help_text='Note de fidélité de 1 à 5')),
                ('localisation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
