# Generated by Django 6.0 on 2026-05-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='entreprise',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='note_fidelite',
            field=models.IntegerField(default=3, help_text='Note de fidélité de 1 à 5'),
        ),
    ]
