# Generated by Django 5.1.15 on 2026-05-15 20:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('transporteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('arrivee', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('trace_itineraire', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('duree_estimee_min', models.IntegerField(blank=True, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('statut_livraison', models.CharField(choices=[('EN_ATTENTE', 'En attente de prise en charge'), ('EN_ROUTE', 'En route'), ('LIVREE', 'Livrée'), ('ECHEC', 'Échec livraison')], default='EN_ATTENTE', max_length=15)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('gain_transporteur', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('commission_plateforme', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('code_confirmation', models.CharField(blank=True, max_length=6)),
                ('signature_client', models.TextField(blank=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='commandes.commande')),
                ('transporteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='transporteurs.transporteur')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PositionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('vitesse_kmh', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='livraisons.livraison')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['livraison', 'timestamp'], name='livraisons__livrais_234477_idx')],
            },
        ),
    ]
