# Generated by Django 6.0 on 2026-05-15 18:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('transporteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_itineraire', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('depart', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('arrivee', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('duree_estimee_min', models.IntegerField(blank=True, null=True)),
                ('statut_livraison', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_ROUTE', 'En route'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livraison', to='commandes.commande')),
                ('transporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='transporteurs.transporteur')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
            },
        ),
    ]
