# Generated by Django 5.1.15 on 2026-05-21 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('total_points_gagnes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_fidelite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte Fidélité',
                'verbose_name_plural': 'Comptes Fidélité',
            },
        ),
        migrations.CreateModel(
            name='TransactionFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GAIN', 'Gain'), ('UTILISATION', 'Utilisation'), ('EXPIRATION', 'Expiration')], max_length=20)),
                ('points', models.PositiveIntegerField()),
                ('raison', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fidelite.comptefidelite')),
            ],
            options={
                'verbose_name': 'Transaction Fidélité',
                'verbose_name_plural': 'Transactions Fidélité',
                'ordering': ['-created_at'],
            },
        ),
    ]
