# Generated by Django 5.1.15 on 2026-05-21 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavorisBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boutique_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_boutiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori Boutique',
                'verbose_name_plural': 'Favoris Boutiques',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'boutique_id')},
            },
        ),
        migrations.CreateModel(
            name='FavorisProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_produits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori Produit',
                'verbose_name_plural': 'Favoris Produits',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'produit_id')},
            },
        ),
    ]
